// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        string
	UserID    int32
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID       int32
	GoogleID string
	Email    string
	Name     string
	Picture  string
}
